=== flohero/se-ssd/20210325/projectlist.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:project="http://www.fh-hagenberg.at/projectteam" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.fh-hagenberg.at/projectteam" elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>
				ProjectTeam Schema - Russian Doll Design
        </xs:documentation>
	</xs:annotation>
	<xs:element name="ProjectList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Project" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Location" type="xs:string"/>
							<xs:element name="Country" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="id" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="l[0-9]{3}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="leader" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="ssn[0-9]{4}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="startdate" type="xs:date" use="required"/>
						<xs:attribute name="enddate" type="xs:date" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueProjectId">
			<xs:selector xpath="project:Project"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
</xs:schema>

=== flohero/se-ssd/20210325/projectlist.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="projectlist.xslt"?>
<ProjectList
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.fh-hagenberg.at/projectteam projectlist.xsd"
	xmlns="http://www.fh-hagenberg.at/projectteam"
	>
	<Project id="l100" leader="ssn1000" startdate="2020-03-12" enddate="2022-05-02">
		<Name>UPRISE</Name>
		<Location>Hagenberg</Location>
		<Country>Österreich</Country>
	</Project>

	<Project id="l300" leader="ssn1002" startdate="2017-12-04" enddate="2023-01-15">
		<Name>CALEMNA</Name>
		<Location>Linz</Location>
		<Country>Österreich</Country>
	</Project>
	<Project id="l400" leader="ssn1003" startdate="2019-10-27" enddate="2021-12-01">
		<Name>CORECTUA</Name>
		<Location>Hagenberg</Location>
		<Country>Österreich</Country>
	</Project>
		<Project id="l200" leader="ssn1000" startdate="2019-02-05" enddate="2020-04-09">
		<Name>VISION</Name>
		<Location>Wels</Location>
		<Country>Österreich</Country>
	</Project>
</ProjectList>
